image: golang:1.11
stages:
  - test

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure -vendor-only

test-my-project:
  stage: test
  script:
    - go test -v -cover ./...
