image: golang:1.11
stages:
  - test

before_script:
    - cd $GOPATH/src
    - mkdir -p github.com/dsummers91
    - cd github.com/dsummers91
    - ln -s $CI_PROJECT_DIR go-bmdc
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - cd ./go-bmdc
    - dep ensure -vendor-only

test-my-project:
  stage: test
  script:
    - cd $GOPATH/src/github.com/dsummers91/go-bmdc
    - go test -v -cover ./...
