version: 0.0
os: linux
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "bmdc-load-balancer"
          ContainerPort: 3000
hooks:
  BeforeInstall:
    - location: codedeploy/BeforeInstall.sh
  AfterInstall:
    - location: codedeploy/AfterInstall.sh
