version: 0.1
            
phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint

  pre_build: 
    commands:
      - go get

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:

      # Build our application
      - go build -o bmdc-server

artifacts:
  files:
    - bmdc-server
    - appspec.yml
    - buildspec.yml
    - config/*
    - codedeploy/*
    - cloudformation/*
