version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - $(aws ecr get-login --region us-west-2 --no-include-email)
      - echo Build started on `date`
      - docker-compose run app go test ./...
      - echo Building the Docker image...          
      - printf "AUTH0_CLIENT_ID=1CtAElrK7eacL7YPIPJqQlhdrpKx5DdR \nAUTH0_DOMAIN=dsummers91.auth0.comAUTH0_CLIENT_SECRET=iNSa_mpam5xaaniCxPOIdvPnSTi7Ge_sDsASfdVwZV5YnSLDGPkPC8sQ7q-xjI6t\nAUTH0_CALLBACK_URL=http://localhost:3000/callback\nAUTH0_AUDIENCE=\nPORT=3000" > .env
      - docker build -t bmdc:lastest .
      - docker tag bmdc:lastest 544793848984.dkr.ecr.us-west-2.amazonaws.com/bmdc:latest      
  post_build:
    commands:
      - echo $REPOSITORY_URI
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 544793848984.dkr.ecr.us-west-2.amazonaws.com/bmdc:latest
      - printf '[{"name":"bmdc","imageUri":"%s"}]' 44793848984.dkr.ecr.us-west-2.amazonaws.com/bmdc:latest > imagedefinitions.json

artifacts:
  files:
    - '.env'
    - 'imagedefinitions.json'
    - 'bmdc-server'
    - 'taskdef.json'
    - 'appspec.yml'
    - 'appspec.yaml'
    - 'buildspec.yml'
    - 'public/*'
    - 'routes/*'
  name: bmdc
