[[constraint]]
  name = "github.com/codegangsta/negroni"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.3"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/flosch/pongo2"
  version = "3.0.0"
